### PR TITLE
371: add 'forgot my password' feature

### PR DESCRIPTION
**Pull request by adp11**

### CODE REVIEW

**Comment by jkcswd** [comment]
Hi Andrew, 

I am trying to run the password reset request and it is not working. Did it work for your email? I am getting the following stack trace:

`
  sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1054, "Unknown column 'user.prt' in 'field list'")
  [SQL: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.name AS user_name, user.validated AS user_validated, user.validation_date AS user_validation_date, user.validation_id AS user_validation_id, user.prt AS user_prt, user.prt_reset_date AS user_prt_reset_date, user.prt_consumption_date AS user_prt_consumption_date 
  FROM user 
  WHERE user.email = %s 
  LIMIT %s]
  [parameters: ('jameskcs1254@gmail.com', 1)]
`

This will need to be sorted out to merge the PR.

Message me or stuart if you get stuck.

**Comment by jkcswd** [comment]
Database may need to be re-seeded to get this to work.

**Comment by adp11** [comment]
@stuart909 I think you can handle the change in the User table structure as I added 3 new columns to the User table.

**Comment by stuart909** [comment]
I ran:

$ flask db migrate --message "added password reset entries to user table"
$ flask db upgrade

**Pull request merged**
