### PR TITLE
360/361/362: fix all small bugs

### PR DESCRIPTION
**Pull request by adp11**
I combined all bug-labeled tickets into 1 commit and 1 PR which is this one.

### CODE REVIEW

**Comment by jkcswd** [comment]
362 is done but I don't think 360/361 are I will talk to stuart and get back to you

**Comment by jkcswd** [comment]
When you changed the company and orders templates to use the oneDiv parent template you need to edit the rest of the template to make it work properly (e.g {% block profilecontent %} needs to become {% block content %} and other things). When I try to go onto the companies and orders lists from the profile screen it just renders a blank page. Also in the admin tool bar it needs to render these pages not the /create pages (needs to go from company/create to just /company). I think if these can get fixed it should be done.

**Comment by adp11** [comment]
@jkcswd I think you can merge it now

**Review by stuart909 — CHANGES_REQUESTED** [review]
1. New Blog is still in the nav and should no longer be.
2. The tools menu blog link should go to /blog/create, which is what new blog used to be
3. There should be no company editor link in nav bar
4. The company editor should be loaded in place of the company link in the tools menu
5. The current company link is just a company list with no div.  Use company editor instead, see 4.
6. Orders is a simple orders list with no div.  We have an orders editor.  Why are we not using it?

**Pull request merged**
